#!/usr/bin/env node
// captions: group word timings into on-screen caption cues (the Creator Stack "2-3 words at a time,
// synced to the transcript"), with reading-speed and line-length limits, and optional key words.
// Output is data, not styling: the brand template decides how cues look. Zero dependencies (Node 18+).
//
// usage: node captions.mjs take.cut.words.json [--max-words 3] [--max-chars 22] [--max-cps 20]
//          [--min-dur 0.35] [--gap-break 0.25] [--key "hand,works"] [--srt]
// writes: take.cut.captions.json · take.cut.captions.js (window.CAPTIONS = …, for HyperFrames)
//         [--srt] take.cut.captions.srt (sentence-level, for YouTube/LinkedIn caption upload)
// Defaults: 22 chars/line fits the strict 9:16 safe width at caption size (BBC 9:16 guidance
// scaled to 875 px); 20 chars/s is Netflix's adult reading speed.

import { readFileSync, writeFileSync } from 'node:fs';

const args = process.argv.slice(2);
const flag = (n, d = null) => { const i = args.indexOf(n); return i === -1 ? d : args[i + 1]; };
const input = args.find((a, i) => !a.startsWith('--') && !(args[i - 1] ?? '').startsWith('--'));
if (!input) { console.error('usage: node captions.mjs take.cut.words.json [--max-words 3] [--key "word,word"] [--srt]'); process.exit(2); }
const MAX_WORDS = +flag('--max-words', 3), MAX_CHARS = +flag('--max-chars', 22), MAX_CPS = +flag('--max-cps', 20);
const MIN_DUR = +flag('--min-dur', 0.35), GAP_BREAK = +flag('--gap-break', 0.25);
const bare = (w) => w.toLowerCase().replace(/[^\p{L}\p{N}']/gu, '');
const WEAK = new Set('a an the of on in to for at by from with and but or my your our his her its their is are was be as into onto'.split(' '));
const keys = new Set((flag('--key', '') || '').split(',').map(bare).filter(Boolean));
const base = input.replace(/\.words\.json$/, '');

const doc = JSON.parse(readFileSync(input, 'utf8'));
const words = [...doc.words].sort((a, b) => a.s - b.s);

// ---- group -----------------------------------------------------------------------------------------
const cues = []; let cur = [];
const textOf = (ws) => ws.map((w) => w.w.trim()).join(' ');
for (const w of words) {
  const prev = cur.at(-1);
  const breakHere = prev && (
    cur.length >= MAX_WORDS ||
    textOf([...cur, w]).length > MAX_CHARS ||
    /[.!?;:,]$/.test(prev.w.trim()) ||
    w.s - prev.e > GAP_BREAK);
  if (breakHere) {
    // Typography: don't strand a small word at the end of a cue when the break is only for length
    // ("zoom in on / my hand." becomes "zoom in / on my hand.").
    const lengthBreak = !/[.!?;:,]$/.test(prev.w.trim()) && w.s - prev.e <= GAP_BREAK;
    const carry = lengthBreak && cur.length > 1 && WEAK.has(bare(prev.w)) ? [cur.pop()] : [];
    cues.push(cur); cur = carry;
  }
  cur.push(w);
}
if (cur.length) cues.push(cur);

// ---- time ------------------------------------------------------------------------------------------
// A cue shows from its first word's start until the next cue starts, capped so it doesn't linger
// through long pauses (end + 0.6 s). Then check the reading speed and flag any cue that's too fast.
const out = cues.map((ws, i) => ({ i, text: textOf(ws), s: ws[0].s, e: ws.at(-1).e, words: ws.map((w) => ({ w: w.w.trim(), s: w.s, e: w.e, key: keys.has(bare(w.w)) })) }));
const warnings = [];
out.forEach((c, i) => {
  const next = out[i + 1];
  const END = doc.duration ?? Infinity;
  const linger = next ? Math.min(next.s, c.e + 0.6) : Math.min(END, c.e + 0.6); // no flicker between cues
  const readable = Math.max(c.e, c.s + MIN_DUR, c.s + c.text.length / MAX_CPS); // long enough to read
  c.e = +Math.min(next ? next.s : END, Math.max(readable, linger)).toFixed(3);
  c.s = +c.s.toFixed(3);
  const cps = c.text.length / Math.max(0.001, c.e - c.s);
  if (cps > MAX_CPS * 1.25) warnings.push(`cue ${i} "${c.text}" at ${c.s}s reads at ${cps.toFixed(0)} chars/s (limit ${MAX_CPS}): split the line or slow the edit`);
});
const unkeyed = [...keys].filter((k) => !out.some((c) => c.words.some((w) => bare(w.w) === k)));
if (unkeyed.length) warnings.push(`key word(s) not found: ${unkeyed.join(', ')}`);

const payload = { source: doc.source, rules: { maxWords: MAX_WORDS, maxChars: MAX_CHARS, maxCps: MAX_CPS }, cues: out };
writeFileSync(`${base}.captions.json`, JSON.stringify(payload, null, 1));
writeFileSync(`${base}.captions.js`, `// generated by edit-kit/captions.mjs from ${input.split(/[\\/]/).pop()}. Do not edit: regenerate.\nwindow.CAPTIONS = ${JSON.stringify(payload)};\n`);

if (args.includes('--srt')) {
  const ts = (t) => { const ms = Math.round(t * 1000); const p = (n, l = 2) => String(n).padStart(l, '0'); return `${p(Math.floor(ms / 3600000))}:${p(Math.floor(ms / 60000) % 60)}:${p(Math.floor(ms / 1000) % 60)},${p(ms % 1000, 3)}`; };
  const sentences = []; let cur2 = [];
  for (const w of words) { cur2.push(w); if (/[.!?]$/.test(w.w.trim()) || textOf(cur2).length > 70) { sentences.push(cur2); cur2 = []; } }
  if (cur2.length) sentences.push(cur2);
  writeFileSync(`${base}.captions.srt`, sentences.map((s, i) => `${i + 1}\n${ts(s[0].s)} --> ${ts(s.at(-1).e)}\n${textOf(s)}\n`).join('\n'));
}
console.log(`captions · ${words.length} words → ${out.length} cues (≤${MAX_WORDS} words, ≤${MAX_CHARS} chars) · ${out.filter((c) => c.words.some((w) => w.key)).length} with a key word\n  → ${base}.captions.json · .captions.js${args.includes('--srt') ? ' · .captions.srt' : ''}`);
for (const w of warnings) console.log(`  ⚠ ${w}`);
