#!/usr/bin/env node
// activate-brand: put exactly one brand's system into a project, so every downstream skill reads
// the right rules and never another brand's.
//   • copies brands/<slug>/brand.md + MOTION.md into the project root (Charlie Hills' skills read them there)
//   • writes frame.md for HyperFrames: YAML tokens from MOTION.md's "Frame tokens" block as frontmatter (HyperFrames
//     treats frame.md frontmatter as brand truth; precedence frame.md → design.md → DESIGN.md) plus a prose digest
//   • stamps each copy with the source hash so drift is detectable
// Zero dependencies (Node 18+).
//
// usage:
//   node activate-brand.mjs <slug> <project-dir> [--studio <studio-root>]   activate a brand in a project
//   node activate-brand.mjs --check <project-dir> [--studio <studio-root>]  verify the copies still match the source
//   node activate-brand.mjs --new <slug> [--studio <studio-root>]           scaffold a new brand from the templates
//   node activate-brand.mjs --list [--studio <studio-root>]                 list brands and their system status

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';

const args = process.argv.slice(2);
const flag = (n) => { const i = args.indexOf(n); return i === -1 ? null : args[i + 1]; };
const positional = args.filter((a, i) => !a.startsWith('--') && !['--studio', '--check', '--new'].includes(args[i - 1]));
const here = dirname(fileURLToPath(import.meta.url));
const sha = (s) => createHash('sha256').update(s).digest('hex').slice(0, 12);
const today = new Date().toISOString().slice(0, 10);

function findStudio(start) {
  let d = resolve(start);
  for (;;) {
    if (existsSync(join(d, 'brands', '_registry.md'))) return d;
    if (existsSync(join(d, 'workspace', 'brands', '_registry.md'))) return join(d, 'workspace');
    const up = dirname(d); if (up === d) return null; d = up;
  }
}
const studio = flag('--studio') ? resolve(flag('--studio')) : findStudio(flag('--check') ?? positional[1] ?? process.cwd());
if (!studio) { console.error('Could not find the studio (a folder containing brands/_registry.md). Pass --studio <path>.'); process.exit(2); }
const brandsDir = join(studio, 'brands');

const STAMP = (slug, file, hash) => `<!-- studio: activated from brands/${slug}/${file} · sha ${hash} · ${today}. Edit the SOURCE, then re-activate. -->\n`;
const stampRe = /^<!-- studio: activated from brands\/([\w-]+)\/([\w.]+) · sha ([0-9a-f]+) · [\d-]+\..*-->\n/;

function status(motion) {
  const rows = motion.split('\n').filter((l) => /^\|\s*\d+\s*\|/.test(l));
  const ask = rows.filter((r) => /ASK ME/.test(r)).length;
  const prop = rows.filter((r) => /PROPOSED/.test(r) && !/ASK ME/.test(r)).length;
  return { fields: rows.length, ask, prop, confirmed: rows.length - ask - prop };
}

// HyperFrames reads frame.md (YAML frontmatter = normative tokens, prose = context). We derive it from
// MOTION.md so there is one source of truth: the frontmatter comes from the ```yaml block under
// "## Frame tokens", and the prose is a digest of the 30 fields.
function frameTokens(motion) {
  const sec = motion.split(/\n## Frame tokens[^\n]*\n/)[1] ?? '';
  const y = sec.match(/```ya?ml\n([\s\S]*?)```/)?.[1] ?? '';
  return y.split('\n').some((l) => /^\s*[a-z-]+:/i.test(l) && !/^\s*#/.test(l)) ? y.trimEnd() : null;
}
function designDigest(slug, brand, motion) {
  const row = (n) => motion.split('\n').find((l) => new RegExp(`^\\|\\s*${n}\\s*\\|`).test(l))?.split('|').slice(2, -1).map((c) => c.trim()) ?? [];
  const val = (n) => { const r = row(n); return r.length ? `${r[1]}${r[2] ? `  _(${r[2]})_` : ''}` : 'ASK ME'; };
  const never = [...(brand.match(/## Never[^\n]*\n([\s\S]*?)(\n## |$)/)?.[1] ?? '').matchAll(/^\d+\.\s+(.+)$/gm)].map((m) => m[1]);
  const example = (motion.split(/\n## 30\.[^\n]*\n/)[1] ?? 'ASK ME').split(/\n## /)[0].trim();
  const tokens = frameTokens(motion);
  const front = tokens ?? `version: alpha\nname: ${slug} · Frame\ndescription: >\n  No confirmed tokens yet: this brand needs intake. Every value is ASK ME; do not invent colours or fonts.`;
  return `---\n${front}\n---\n\n# frame.md · ${slug}

> Generated by activate-brand from \`brands/${slug}/MOTION.md\` and \`brand.md\`. **Do not edit here.**
> Edit the source brand files and re-activate. Values marked PROPOSED are drafts awaiting
> Bianno's confirmation. ASK ME means the value is unknown: ask, never invent.

## Colour
- Palette: ${val(1)}
- Hierarchy: ${val(2)}

## Typography
- Families: ${val(3)}
- Sizes: ${val(4)}
- Weights: ${val(5)} · Tracking: ${val(6)} · Leading: ${val(7)}
- Spacing / safe inset: ${val(8)}

## Motion
- Frame rate: ${val(9)}
- Timing: ${val(10)}
- Entrances: ${val(11)}
- Exits: ${val(12)}
- Transitions: ${val(13)}
- Easing: ${val(14)}
- Camera: ${val(15)} · Depth: ${val(16)}

## Surface
- Texture: ${val(17)} · Grain: ${val(18)} · Lighting: ${val(19)}
- Material: ${val(20)} · Shadows: ${val(21)} · Borders: ${val(22)} · Shapes: ${val(23)}
- Images: ${val(24)}
- UI: ${val(25)}

## Sound
- ${val(26)}

## Accessibility
- ${val(27)}
- Reduced motion: ${val(28)}

## Never
${(never.length ? never : ['ASK ME']).map((n) => `- ${n}`).join('\n')}
- ${val(29)}

## Reference example (shot by shot)
${example}
`;
}

// ---- commands -------------------------------------------------------------------------------------
if (args.includes('--list')) {
  for (const slug of readdirSync(brandsDir).filter((d) => existsSync(join(brandsDir, d, 'MOTION.md')))) {
    const s = status(readFileSync(join(brandsDir, slug, 'MOTION.md'), 'utf8'));
    console.log(`${slug.padEnd(20)} ${s.confirmed} confirmed · ${s.prop} proposed · ${s.ask} ASK ME  (of ${s.fields})`);
  }
  process.exit(0);
}

if (flag('--new')) {
  const slug = flag('--new');
  if (!/^[a-z0-9-]+$/.test(slug)) { console.error('slug must be kebab-case'); process.exit(2); }
  const d = join(brandsDir, slug);
  if (existsSync(d)) { console.error(`brands/${slug} already exists`); process.exit(2); }
  mkdirSync(join(d, 'assets'), { recursive: true });
  const name = slug.split('-').map((w) => w[0].toUpperCase() + w.slice(1)).join(' ');
  for (const f of ['brand', 'MOTION']) writeFileSync(join(d, `${f}.md`), readFileSync(join(here, '..', 'templates', `${f}.template.md`), 'utf8').replaceAll('{{BRAND}}', name));
  console.log(`created brands/${slug}/ (brand.md, MOTION.md, assets/). Next: run intake, then add a row to brands/_registry.md`);
  process.exit(0);
}

if (flag('--check')) {
  const proj = resolve(flag('--check')); let drift = 0;
  for (const file of ['brand.md', 'MOTION.md']) {
    const p = join(proj, file);
    if (!existsSync(p)) { console.log(`✖ ${file} missing: run activate-brand`); drift++; continue; }
    const m = readFileSync(p, 'utf8').match(stampRe);
    if (!m) { console.log(`⚠ ${file} has no activation stamp (hand-written or from Charlie's brand-intake?)`); continue; }
    const src = join(brandsDir, m[1], m[2]);
    const now = existsSync(src) ? sha(readFileSync(src, 'utf8')) : null;
    if (now === m[3]) console.log(`✔ ${file} matches brands/${m[1]} (sha ${m[3]})`);
    else { console.log(`✖ ${file} is stale: source changed (${m[3]} → ${now}). Re-activate.`); drift++; }
  }
  process.exit(drift ? 1 : 0);
}

const [slug, projArg] = positional;
if (!slug || !projArg) { console.error('usage: node activate-brand.mjs <slug> <project-dir> | --check <project-dir> | --new <slug> | --list'); process.exit(2); }
const src = join(brandsDir, slug);
if (!existsSync(join(src, 'MOTION.md'))) { console.error(`No brand "${slug}". Known: ${readdirSync(brandsDir).filter((d) => existsSync(join(brandsDir, d, 'MOTION.md'))).join(', ')}`); process.exit(2); }
const proj = resolve(projArg); mkdirSync(proj, { recursive: true });

// Refuse to overwrite a different brand's activation silently.
for (const file of ['brand.md', 'MOTION.md']) {
  const p = join(proj, file);
  if (existsSync(p)) { const m = readFileSync(p, 'utf8').match(stampRe); if (m && m[1] !== slug && !args.includes('--force')) { console.error(`✖ ${proj} is already activated for "${m[1]}". Brands never share a project. Use --force only if this project really changed brand.`); process.exit(1); } }
}
const brand = readFileSync(join(src, 'brand.md'), 'utf8');
const motion = readFileSync(join(src, 'MOTION.md'), 'utf8');
writeFileSync(join(proj, 'brand.md'), STAMP(slug, 'brand.md', sha(brand)) + brand);
writeFileSync(join(proj, 'MOTION.md'), STAMP(slug, 'MOTION.md', sha(motion)) + motion);
writeFileSync(join(proj, 'frame.md'), designDigest(slug, brand, motion));
const s = status(motion);
console.log(`activated "${slug}" → ${proj}\n  brand.md · MOTION.md · frame.md (HyperFrames tokens${frameTokens(motion) ? '' : ': none yet, needs intake'})\n  system: ${s.confirmed} confirmed · ${s.prop} proposed · ${s.ask} ASK ME (of ${s.fields})`);
if (s.ask) console.log(`  ⚠ ${s.ask} field(s) are ASK ME: ask Bianno before relying on them; never fill them with guesses.`);
