/**
 * Deterministic, hand-written crisis response (spec 04 §2).
 * This text is NEVER generated by a model. Resource directory is versioned
 * config — extend per launch region.
 */

export const CRISIS_RESOURCES: Record<string, string[]> = {
  US: ["988 Suicide and Crisis Lifeline: call or text 988"],
  EU: [
    "Emergency services: 112",
    "Emotional support helplines: 116 123 in many EU countries",
  ],
  DEFAULT: [
    "findahelpline.com lists free, confidential support lines for your country",
  ],
};

export function crisisResponse(region: string | null): string {
  const resources =
    CRISIS_RESOURCES[region ?? ""] ?? CRISIS_RESOURCES["DEFAULT"] ?? [];
  return [
    "Thank you for telling me this. What you're carrying right now matters more than any plan or goal.",
    "I can't help with this the way a person can, and you deserve real support:",
    ...resources.map((r) => `• ${r}`),
    "If you are in immediate danger, please contact emergency services now.",
    "Dawnward will be here when you're ready. There is no plan today, and that is the right plan.",
  ].join("\n");
}
